[package]
name = "scte35"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitter = "0.6"

[dev-dependencies]
base64 = "0.21"
pretty_assertions = "1.3"
